Update AB layout to match Aqua layout (ad spots) and create 'Daily Dig' section/ad
parameter1/ab-media-newsletters pull request #109
Opened 2024-01-30 19:48 UTC by jwade1327

<img width="801" alt="Screen Shot 2024-01-30 at 10 31 04 AM" src="https://github.com/parameter1/ab-media-newsletters/assets/64623209/21fdaa66-13eb-43a4-824c-fdaf359a32cc">
<img width="783" alt="Screen Shot 2024-01-30 at 10 31 24 AM" src="https://github.com/parameter1/ab-media-newsletters/assets/64623209/3dfef0ae-b8d9-4fcc-bea6-123687faf19a">

2024-01-30 19:49 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [AB: Enews ad look, Sponsored Content look change requests](https://trello.com/c/9IOruuu9/634-ab-enews-ad-look-sponsored-content-look-change-requests)

2024-01-31 14:06 UTC, Shinsina requested changes
If my understanding of what's actually going on here is incorrect do let me know.

2024-01-31 14:06 UTC, Shinsina commented on packages/common/components/blocks/ad/promotion-daily-dig.marko
> +$ content.labels = ["Sponsored"];
This doesn't appear to be actively used by the daily-dig-block, is there a reason it's included here?

2024-01-31 14:06 UTC, Shinsina commented on packages/common/components/blocks/content/daily-dig.marko
> +import { get, getAsArray } from "@parameter1/base-cms-object-path";
Due to ` $ const labels = getAsArray(content, "labels");` being the only thing using that and as far as I can tell `labels` goes unused here `getAsArray` can likely be removed here

2024-01-31 14:06 UTC, Shinsina commented on packages/common/components/blocks/content/daily-dig.marko
> +$ const primaryColor = defaultValue(get(newsletterConfig, "primaryColor"), "#103A57");
These both can be removed as this is the only thing using `newsletterConfig` and `primaryColor` isn't used anywhere

2024-01-31 14:43 UTC, Shinsina approved these changes

2024-01-31 14:43 UTC, merged