Update AQUA's permission statement in footer
parameter1/ab-media-newsletters pull request #71
Opened 2023-02-09 17:15 UTC by jwade1327

AQUA (doesn't repeat magazine):
<img width="714" alt="Screen Shot 2023-02-09 at 11 12 33 AM" src="https://user-images.githubusercontent.com/64623209/217888141-fb0973cd-6549-409c-973c-d814bb7726a6.png">
WFB (publication name & magazine):
<img width="742" alt="Screen Shot 2023-02-09 at 11 12 44 AM" src="https://user-images.githubusercontent.com/64623209/217888148-6b24dbd0-cd10-45b6-adcf-8e713087a25a.png">

2023-02-09 17:15 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [AQUA Today footer wording correction.](https://trello.com/c/rDfiiTba/445-aqua-today-footer-wording-correction)

2023-02-10 15:43 UTC, Shinsina requested changes

2023-02-10 15:43 UTC, Shinsina commented on packages/common/components/blocks/footer.marko
> +              </else>
Instead of doing all this would it make more sense to do a find/replace for 'Magazine' in `publicationName`? something like `publicationName.replace(/ Magazine$/, '')`

2023-02-10 16:07 UTC, Shinsina approved these changes

2023-02-10 16:07 UTC, Shinsina approved these changes

2023-02-10 16:08 UTC, merged